[package]
name = "sixtyfps-rendering-backend-gl"
version = "0.0.1"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "OpenGL rendering backend for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
path = "lib.rs"

[dependencies]
sixtyfps-corelib = { version="=0.0.1", path = "../../corelib" }
lyon = { version = "0.16" }
image = { version = "0.23.4", default-features = false }
cgmath = "0.17.0"
vtable = { path = "../../../helper_crates/vtable" }
pathfinder_geometry = "0.5.1"
guillotiere = "0.6"
itertools = "0.9.0"
smallvec = "1.4.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { version = "0.3", package = "web-sys", features=["console"] }
wasm-bindgen = { version = "0.2" }
winit = { version = "0.23", features = ["web-sys"] }
# Use a git version until Context::tex_sub_image_2d_with_html_image is released.
glow = { git = "https://github.com/grovesNL/glow", rev = "b31cce3a5fadb8ec216bd835b5ba5302873b2886", features = ["web-sys"], default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = { version = "0.23" }
glutin = { version = "0.25" }
# Use a git version until Context::tex_sub_image_2d_with_html_image is released.
glow = { git = "https://github.com/grovesNL/glow", rev = "b31cce3a5fadb8ec216bd835b5ba5302873b2886", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = { version = "0.24.0" }

